//
// Copyright (c) Vatsal Manot
//

import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros
import SwiftSyntaxUtilities

public struct KeyAutogeneratedMacro: AttachedMacro {
    
}

extension KeyAutogeneratedMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let variableDeclaration = declaration.as(VariableDeclSyntax.self) else {
            return []
        }
        
        guard let identifierBinding = variableDeclaration.soleIdentifierBinding else {
            context.diagnose(
                Diagnostic(
                    node: Syntax(node),
                    message: DiagnosticMessage.missingAnnotation
                )
            )
            
            return []
        }

        var binding = identifierBinding.binding
        let identifier = identifierBinding.identifier.text
        
        binding.pattern = PatternSyntax(IdentifierPatternSyntax(identifier: .identifier("defaultValue")))
        
        let isOptionalType = binding.typeAnnotation?.type.is(OptionalTypeSyntax.self) ?? false
        let hasDefaultValue = binding.initializer != nil
        
        guard isOptionalType || hasDefaultValue else {
            context.diagnose(Diagnostic(node: Syntax(node), message: DiagnosticMessage.noDefaultArgument))
            return []
        }
        
        return [
            """
            internal final class _KeyAutogenerated_\(raw: identifier): _HeterogenousDictionaryKeyType {
                static var \(binding)
            
                static var _swift_variableIdentifier: String {
                    "\(raw: identifier)"
                }
            }
            """
        ]
    }
}

extension KeyAutogeneratedMacro: AccessorMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingAccessorsOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AccessorDeclSyntax] {
        
        // Skip declarations other than variables
        guard let variableDeclaration = declaration.as(VariableDeclSyntax.self) else {
            return []
        }
        
        guard let identifierBinding = variableDeclaration.soleIdentifierBinding else {
            context.diagnose(Diagnostic(node: Syntax(node), message: DiagnosticMessage.missingAnnotation))
            return []
        }

        let identifier = identifierBinding.identifier.text
        
        return [
            """
            get {
                self[_KeyAutogenerated_\(raw: identifier).self]
            }
            """,
            """
            set {
                self[_KeyAutogenerated_\(raw: identifier).self] = newValue
            }
            """
        ]
    }
}

extension KeyAutogeneratedMacro {
    enum DiagnosticMessage: String, SwiftDiagnostics.DiagnosticMessage {
        case noDefaultArgument = "No default value provided."
        case missingAnnotation = "No annotation provided."
        case notAnIdentifier = "Identifier is not valid."
        
        var message: String {
            rawValue
        }

        var diagnosticID: MessageID {
            .init(domain: "com.vmanot.SwallowMacros.KeyAutogenerated", id: String(describing: self))
        }

        var severity: DiagnosticSeverity {
            .error
        }
    }
}
