//
// Copyright (c) Vatsal Manot
//

import Swift

@attached(peer, names: prefixed(_KeyAutogenerated_))
@attached(accessor, names: named(get), named(set))
public macro KeyAutogenerated() = #externalMacro(
    module: "SwallowMacros",
    type: "KeyAutogeneratedMacro"
)

@attached(memberAttribute)
public macro KeysAutogenerated() = #externalMacro(
    module: "SwallowMacros",
    type: "KeysAutogeneratedMacro"
)
