//
// Copyright (c) Vatsal Manot
//

import Swift

/// Relies on `_HeterogenousDictionaryKeyType` of `HeterogeneousDictionaryProtocol`.
@attached(memberAttribute)
public macro KeysAutogenerated() = #externalMacro(
    module: "SwallowMacros",
    type: "KeysAutogeneratedMacro"
)

/// This macro, `@KeyAutogenerated`, is added automatically to each member of the declaration that `@KeysAutogenerated` is attached to.
///
/// It is not meant to be used directly.
@attached(peer, names: prefixed(_KeyAutogenerated_))
@attached(accessor, names: named(get), named(set))
public macro KeyAutogenerated() = #externalMacro(
    module: "SwallowMacros",
    type: "KeyAutogeneratedMacro"
)
