//
// Copyright (c) Vatsal Manot
//

import SwiftCompilerPlugin
import SwiftSyntaxMacros

@main
public struct module: CompilerPlugin {
    public static var domain: String {
        "com.vmanot.SwallowMacros"
    }
    
    public let providingMacros: [Macro.Type] = [
        AssociatedObjectMacro.self,
        AddCaseBooleanMacro.self,
        DebugLogMacro.self,
        DebugLogMethodMacro.self,
        DeclarationScopeMacro.self,
        GenerateDuplicateMacro.self,
        GenerateTypeEraserMacro.self,
        HadeanIdentifierMacro.self,
        HashableMacro.self,
        KeyAutogeneratedMacro.self,
        KeysAutogeneratedMacro.self,
        KeyPathIterableMacro.self,
        ManagedActorMacro.self,
        ManagedActorMacro2.self,
        ManagedActorMethodMacro.self,
        ManagedActorMethodMacro2.self,
        MemoizedPropertyMacro.self,
        MetatypeExpressionMacro.self,
        InitializeInlineXCTestCasesMacro.self,
        OnceMacro.self,
        OptionSetMacro.self,
        RuntimeConversionMacro.self,
        RuntimeDiscoverableMacro.self,
        _StaticProtocolMember.self,
        SingletonMacro.self,
        TestMacro.self,
        TryMacro.self,
        TryAwaitMacro.self,
        
        _DeveloperNotesMacro.self,
        _InternalTestMacro.self,
        _CodesectionMacro.self,
    ]
    
    public init() {
        
    }
}
