name: Generate Documentation
on:
  push:
    branches: [ master, docc-generation]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Documentation
      run: |
        if ! sh ./scripts/generate-docc.sh; then
          echo "Documentation generation failed"
          exit 1
        fi

    - name: Upload to Cloudflare
      run: |
        if ! sh ./scripts/upload_to_cloudflare.sh; then
          echo "Cloudflare upload failed"
          exit 1
        fi