name: Xcodebuild Check
on:
  pull_request:
    branches: [ main ]  # Adjust this if you want it to run on PRs to different branches
  workflow_dispatch:    # Keep the manual trigger

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - name: Install xcbeautify
      run: |
        brew install xcbeautify

    - name: Run xcodebuild
      run: |
        xcrun xcodebuild -scheme Swallow -destination generic/platform='macOS' build | xcbeautify --renderer github-actions